name: Upload Python Package and Generate Changelog

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This fetches all history for all branches and tags

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Generate Changelog
        run: |
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"- %s%n%b" > CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md" || echo "No changes to commit"
          git fetch origin master
          git checkout master
          git merge --no-ff ${{ github.sha }} -m "Merge tag ${{ github.ref }} into master"
          git push origin master

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}